// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sidebar': string;
  'sidebarNav': string;
}
export const cssExports: CssExports;
export default cssExports;
