// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headerCart': string;
  'headerContainer': string;
  'headerLogo': string;
  'headerNumberGoods': string;
  'iconCart': string;
}
export const cssExports: CssExports;
export default cssExports;
