// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'cardAction': string;
  'cardContent': string;
  'cardDesc': string;
  'cardHeader': string;
  'cardHeaderBtn': string;
  'cardHeaderBtnCreate': string;
  'cardHeaderBtnRemove': string;
  'cardHeaderImg': string;
  'cardTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
